export const sculptureList = [
    {
       id: 100 ,
       name:' วงดนตรี ',
       artist:'กะลา',
       description:'วงโปรดของฉัน',
       url:'/images/กะลา.jpg',
       alt:'เป็นเพลงยุคเก่าที่บนปัจุบันชอบฟัง',
    },
    {
      id: 200 ,
       name:' วงดนตรี ',
       artist:'Silly fools',
       description:'วงโปรดของฉัน',
       url:'/images/4eed1b8e770.jpg',
       alt:'วงเก่าที่ยังมีอยู่ในปัจจุบันแต่เปลี่ยนนักร้องคนใหม่',
    },
    {
      id: 300 ,
       name:' วงดนตรี ',
       artist:' กางเกง ',
       description:'วงที่หลายๆคนที่รู้จักในวงการเพลง',
       url:'/images/กางเกง.jpg',
       alt:'วงที่สมัยก่อนใครๆก็ต่างรู้จัก',
    },
    {
      id: 400 ,
       name:' การ์ตูน ',
       artist:' ยอดนักสืบจิ๋ว โคนัน ',
       description:'ถึงตัวจะเด็กแต่สมองเขาก็ผู้ใหญ่',
       url:'/images/27cf9de0-1f2a-11ef-9d5c-8f8eda0ae938_webp_original.webp',
       alt:'การ์ตูนวัยเด็กที่ใครๆก็รู้จักเขาดี',
    },
   {
      id: 500 ,
       name:' การ์ตูน ',
       artist:' ชินจัง ',
       description:'เด็กที่ทะลิ้งชอบโชว์ตูด',
       url:'/images/Crayon_Shin-chan.jpg',
       alt:'การ์ตูนที่อยู่อย่างยาวนานและยังมีอยู่ในปัจจุบัน',
   },
   {
      id: 600 ,
       name:' การ์ตูน ',
       artist:' DORAEMON ',
       description:'หุ่นยนตร์แมว ที่มีของวิเศษมากมาย',
       url:'/images/ม่อน.jpg',
       alt:'เป็นแก๊งค์เด็กวัยประถมที่ชอบการผจญภัย',
   },
   ];